import axios from 'axios';

const BASE_URL = process.env.REACT_APP_API_URL || 'http://localhost:8080/api';

const api = axios.create({
  baseURL: BASE_URL,
  headers: { 'Content-Type': 'application/json' },
});

// ─── Request interceptor ─────────────────────────────────────────────────────
// Two jobs:
//  1. Attach the JWT token on every request.
//  2. When the request body is FormData, DELETE the Content-Type header so the
//     browser's XHR layer can set it to:
//       multipart/form-data; boundary=<auto-generated>
//     If we leave the Axios-instance default "application/json" header in place,
//     Axios sets that header explicitly via XHR.setRequestHeader() — which means
//     Spring Boot's StandardServletMultipartResolver never sees a valid boundary,
//     refuses to parse the body, and the request fails with Network Error (POST)
//     or 403 (PUT). Deleting the header here lets the browser do the right thing.
api.interceptors.request.use(
  (config) => {
    // Attach JWT
    const token = localStorage.getItem('fundrise_token');
    if (token) config.headers.Authorization = `Bearer ${token}`;
    else console.warn('No JWT token found for:', config.method?.toUpperCase(), config.url);

    // Fix multipart: remove Content-Type so the browser sets it with the boundary
    if (config.data instanceof FormData) {
      delete config.headers['Content-Type'];
    }

    return config;
  },
  (error) => Promise.reject(error)
);

// ─── Response interceptor ────────────────────────────────────────────────────
// Redirect to /login on 401.
api.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response?.status === 401) {
      localStorage.removeItem('fundrise_token');
      localStorage.removeItem('fundrise_user');
      if (!window.location.pathname.includes('/login')) {
        window.location.href = '/login';
      }
    }
    return Promise.reject(error);
  }
);

// --- Auth API ---
export const authAPI = {
  register: (data) => api.post('/auth/register', data),
  login:    (data) => api.post('/auth/login', data),
};

// --- Campaign API ---
export const campaignAPI = {
  getAll:        (params)                => api.get('/campaigns', { params }),
  getFeatured:   ()                      => api.get('/campaigns/featured'),
  search:        (q, page = 0, size = 12) =>
                   api.get('/campaigns/search', { params: { q, page, size } }),
  getByCategory: (category, page = 0, size = 12) =>
                   api.get(`/campaigns/category/${category}`, { params: { page, size } }),
  getById:       (id)                    => api.get(`/campaigns/${id}`),
  getMyCampaigns:(page = 0, size = 10)   =>
                   api.get('/campaigns/my-campaigns', { params: { page, size } }),
  // FormData — Content-Type is handled by the request interceptor above
  create:        (formData)              => api.post('/campaigns', formData),
  update:        (id, formData)          => api.put(`/campaigns/${id}`, formData),
  delete:        (id)                    => api.delete(`/campaigns/${id}`),
};

// --- Donation API ---
export const donationAPI = {
  createPaymentIntent:  (data)                        => api.post('/donations/payment-intent', data),
  getCampaignDonations: (campaignId, page = 0, size = 10) =>
                          api.get(`/campaigns/${campaignId}/donations`, { params: { page, size } }),
  getMyDonations:       ()                            => api.get('/donations/my-donations'),
};

// --- User API ---
export const userAPI = {
  getMe:         ()         => api.get('/users/me'),
  getById:       (id)       => api.get(`/users/${id}`),
  // FormData — Content-Type is handled by the request interceptor above
  updateProfile: (formData) => api.put('/users/me', formData),
};

// --- Admin API ---
export const adminAPI = {
  getDashboard:     ()                  => api.get('/admin/dashboard'),
  getUsers:         ()                  => api.get('/admin/users'),
  toggleUserStatus: (id)                => api.patch(`/admin/users/${id}/toggle-status`),
  getCampaigns:     (page = 0, size = 20) =>
                      api.get('/admin/campaigns', { params: { page, size } }),
  deleteCampaign:   (id)                => api.delete(`/admin/campaigns/${id}`),
};

export default api;
